### ISSUE TITLE
Align nav buttons in center  of sidebar

### ISSUE THREAD

**Issue by Andyy-18** [Andyy-18/Basic-Portfolio#1]

**Comment by rizzuraj** [comment]
Hey!Can you provide the description and assign this issue to me ?

**Comment by Andyy-18** [comment]
Sure @rrsingh11 
Go ahead.
Align the nav buttons in the center of the movable navbar .

**Comment by rizzuraj** [comment]
Hello @Andyy-18 ,
I hope this is what you wanted.

![image](https://user-images.githubusercontent.com/86000208/194773373-1e9753d4-c084-44e2-a6c3-cc541f0c5b4f.png)

**Comment by rizzuraj** [comment]
Checkout #5 for reference.

**Comment by Andyy-18** [comment]
@rrsingh11 Yeah .
