### ISSUE TITLE
Add some cool background-images  without effecting its responsiveness and alignments

### ISSUE THREAD

**Issue by Andyy-18** [Andyy-18/Basic-Portfolio#2]
Add images to improve it's style in About and Contact pages.
Remember the Responsiveness and Alignments of movable sidebar should  remain the same.

Attach screenshots after your works. Thank you.

**Comment by FinnKr** [comment]
I could do this. Do you mind assigning it to me? And do you have any preferences regarding the type of images?

**Comment by igbaras** [comment]
I can work with this, please provide the details

**Comment by Andyy-18** [comment]
@FinnKr bro add a background image to the About and contact pages.

**Comment by Andyy-18** [comment]
@Tiansing go ahead.
Add some cool hd images in thr About and Contact pages.

**Comment by igbaras** [comment]
@Andyy-18 I have submitted a new PR #6 you can check it out. I also still working on your contacts page, I'll try to follow up that latur. Thank you

**Comment by ghost** [comment]
I want to work on this can you assign me a issue

**Comment by Andyy-18** [comment]
@mnamesujit sure
Add some style for Contact page.

**Comment by Andyy-18** [comment]
@mnamesujit Are you doing?
